### PR TITLE
tail from end of file

### PR DESCRIPTION
**Pull request by itshikanov**

### CODE REVIEW

**Comment by itshikanov** [comment]
When the exporter is started, he reads the whole file, from the first line. When you restart the exporter, you receive splash on chart with 10000+ values.  
The fix reads the file since the end and rate() function work properly.

**Comment by paskal** [comment]
Looks promising, but (obviously) it breaks tests, could you please fix them as well?

**Comment by itshikanov** [comment]
> Looks promising, but (obviously) it breaks tests, could you please fix them as well?
I think that tests, read the file since the beginning. Thats why they breaks.

**Comment by martin-helmich** [comment]
:+1: Thanks for the contribution (and sorry for the late response).

The failing tests actually uncovered an interesting edge case: In the test cases, the exporter is started _first_, and _then_ the access log file is written (which means that the tests _should_ pass, even with this change).

The issue was that the access log file was _still_ read from EOF even if it did not exist when the exporter was started. IMO the correct behaviour would be to...

1. read the file from the end if it already existed when the exporter started
2. read the entire file from the beginning if it only popped up when the exporter was already running

Fixed this in 25a4901

**Pull request merged**
