### PR TITLE
Implement unix socket for syslog

### PR DESCRIPTION
**Pull request by jkroepke**

### CODE REVIEW

**Comment by jkroepke** [comment]
@martin-helmich please let me know, if I can help here.

**Comment by jkroepke** [comment]
@martin-helmich I would appreciate a review here.

**Comment by martin-helmich** [comment]
Apologies that this has been laying around for a while 🙏  -- I'll give it a look right now.

**Review by martin-helmich — APPROVED** [review]
LGTM :+1: -- I added two additional commits with a new test case, and some refactorings, though

**Pull request merged**
